# Generated by Django 3.1.1 on 2023-02-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230214_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='home_gold',
            new_name='home_bar',
        ),
    ]
