# Generated by Django 3.1.1 on 2023-02-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20230214_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='home_bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='home_coin',
            field=models.BooleanField(default=False),
        ),
    ]
