# Generated by Django 3.1.1 on 2023-02-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20230214_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_sellers',
            field=models.BooleanField(default=False),
        ),
    ]
