# Generated by Django 3.1.1 on 2023-02-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_deals'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_original',
            field=models.FloatField(null=True),
        ),
    ]
