# Generated by Django 3.1.1 on 2023-02-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20230225_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='home_nugget',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='home_ornament',
            field=models.BooleanField(default=False),
        ),
    ]
